name: Run Tests

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the tests on
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          FLASK_CONFIG: testing
        run: |
          nohup flask run &
          sleep 5
          python run_tests.py
