name: Regression Tests

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the tests on
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          sleep 10  # Wait for Docker to start
          docker --version

      - name: Run regression tests on Linux
        if: runner.os == 'Linux'
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          FLASK_CONFIG: testing
        run: |
          nohup flask run &
          sleep 5
          python run_tests.py -v

      - name: Run regression tests on Windows
        if: runner.os == 'Windows'
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          FLASK_CONFIG: testing
        run: |
          start /B flask run
          timeout /t 5
          python run_tests.py -v

      - name: Run regression tests on macOS
        if: runner.os == 'macOS'
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          FLASK_CONFIG: testing
        run: |
          nohup flask run &
          sleep 5
          python run_tests.py -v

      - name: Print environment variables
        run: printenv

